version: '3.3'

services:
  log-api:
    build:
      context: .
    volumes:
      - type: volume
        source: /var/log
        target: /opt/var/log
        read_only: true
    command: ["/opt/app/result/bin/logAPI", "0.0.0.0", "3000", "/opt/var/log"]
    restart: on-failure
    networks:
      - lognet

  nginx:
    image: tutum/nginx
    ports:
        - "443:443"
    volumes:
        - ./nginx/default:/etc/nginx/sites-available/default
        - ./nginx/default:/etc/nginx/sites-enabled/default
        - ./certs/:/etc/nginx/certs/
    restart: on-failure
    networks:
      - lognet

networks:
  lognet:
    driver: bridge
