version: '2'

services:
  log-api:
    build:
      context: .
    volumes:
      - /var/log:/var/log
    ports:
      - 3000:3000
    command: ["/opt/app/result/bin/logAPI", "0.0.0.0", "3000", "/var/log"]
